trigger: none
pr: none

parameters:
- name: outputSpec
  displayName: Output OpenAPI spec
  type: string
  default: Internal Dev Portal.yaml
- name: includeProdRoutes
  displayName: Include prod-specific route templates
  type: boolean
  default: false

stages:
- template: pipelines/dev-portal.yml
  parameters:
    devportalEnvFile: kong/env/user/devportal.env
    outputSpec: ${{ parameters.outputSpec }}
    includeProdRoutes: ${{ parameters.includeProdRoutes }}
