#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 3 ] && [ "$#" -ne 4 ]; then
  echo "Usage: $0 <template_dir> <env_file> <output_dir> [override_env_file]"
  exit 1
fi

TEMPLATE_DIR="$1"
ENV_FILE="$2"
OUTPUT_DIR="$3"
OVERRIDE_ENV_FILE="${4:-}"

test -d "$TEMPLATE_DIR" || { echo "Template directory not found: $TEMPLATE_DIR"; exit 1; }
test -f "$ENV_FILE" || { echo "Environment file not found: $ENV_FILE"; exit 1; }

ENV_BASENAME="$(basename "$ENV_FILE")"
ENV_NAME="${ENV_BASENAME%-onprem.env}"
ENV_PARENT_DIR="$(cd "$(dirname "$ENV_FILE")" && pwd)"
SYSTEM_ENV_FILE="$(cd "$ENV_PARENT_DIR/.." && pwd)/system/${ENV_NAME}-system.env"

set -a
if [ -f "$SYSTEM_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$SYSTEM_ENV_FILE"
fi
# shellcheck disable=SC1090
source "$ENV_FILE"
if [ -n "$OVERRIDE_ENV_FILE" ]; then
  test -f "$OVERRIDE_ENV_FILE" || { echo "Override file not found: $OVERRIDE_ENV_FILE"; exit 1; }
  # shellcheck disable=SC1090
  source "$OVERRIDE_ENV_FILE"
fi
set +a

required_vars=(
  CONTROL_PLANE_NAME
  ENV_TAG_LOWER
  INTERNAL_TLS_HOST
  PUBLIC_HOST_PRIMARY
  AML_REST_SERVICE_HOST
  BANCAWEB_SERVICE_HOST
  CLAIMHISTORY_STORM_SERVICE_HOST
  KYC_WSMANAGER_SERVICE_HOST
  GET_TOKEN_SERVICE_NAME
  GET_TOKEN_SERVICE_HOST
  ISSUER_URL
  REDIS_HOST
  REDIS_PASSWORD
  REDIS_PARTIAL_ID
  REDIS_PARTIAL_NAME
  REDIS_PARTIAL_TYPE
  REDIS_PARTIAL_HOST
  REDIS_PARTIAL_PASSWORD
  REDIS_PARTIAL_SENTINEL_MASTER
  REDIS_PARTIAL_SENTINEL_NODES
  REDIS_PARTIAL_SENTINEL_PASSWORD
  REDIS_PARTIAL_SENTINEL_ROLE
  REDIS_PARTIAL_SENTINEL_USERNAME
  REDIS_CACHE_PARTIAL_ID
  REDIS_CACHE_PARTIAL_NAME
  REDIS_CACHE_HOST
  REDIS_CACHE_PASSWORD
  REDIS_CACHE_SENTINEL_MASTER
  REDIS_CACHE_SENTINEL_NODES
  REDIS_CACHE_SENTINEL_PASSWORD
  REDIS_CACHE_SENTINEL_ROLE
  REDIS_CACHE_SENTINEL_USERNAME
  VAULT_CONFIG_STORE_ID
  STANDARD_AMLA_API_RATE_LIMIT_MINUTE
  STANDARD_AMLA_API_RATE_LIMIT_HOUR
  STANDARD_BANCA_PORTAL_RATE_LIMIT_MINUTE
  STANDARD_BANCA_PORTAL_RATE_LIMIT_HOUR
  STANDARD_CLAIM_HISTORY_RATE_LIMIT_MINUTE
  STANDARD_CLAIM_HISTORY_RATE_LIMIT_HOUR
  STANDARD_AMLA_API_USER_CUSTOM_ID
  STANDARD_BANCA_PORTAL_USER_CUSTOM_ID
  STANDARD_CLAIM_HISTORY_USER_CUSTOM_ID
)

for var_name in "${required_vars[@]}"; do
  test -n "${!var_name:-}" || { echo "Missing required variable in $ENV_FILE: $var_name"; exit 1; }
done

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -R "$TEMPLATE_DIR"/. "$OUTPUT_DIR"/

rm -f "$OUTPUT_DIR/partials/003-redis-partial-name-prod.yaml"
rm -f "$OUTPUT_DIR/partials/004-redis-partial-name-prod-dr.yaml"
rm -f "$OUTPUT_DIR/partials/005-redis-cache-partial-name-prod-dr.yaml"
rm -f "$OUTPUT_DIR/routes/005-kyc-wsmanager-api-prod.yaml"
rm -f "$OUTPUT_DIR/consumers/001-standard-amla-api-user-prod.yaml"
rm -f "$OUTPUT_DIR/consumers/002-standard-banca-portal-user-prod.yaml"
rm -f "$OUTPUT_DIR/consumers/003-standard-claim-history-user-prod.yaml"

find "$OUTPUT_DIR" -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.md" \) -print0 | while IFS= read -r -d '' file; do
  perl -0pe '
    my $secondary = $ENV{"PUBLIC_HOST_SECONDARY"} // "";
    s/^([ \t]*)-[ \t]*"?__OPTIONAL_PUBLIC_HOST_SECONDARY_TLS__"?[ \t]*\r?\n/
      $secondary ne "" ? $1 . "- \"" . $secondary . ":443\"\n" : ""/gme;
    s/^([ \t]*)-[ \t]*"?__OPTIONAL_PUBLIC_HOST_SECONDARY__"?[ \t]*\r?\n/
      $secondary ne "" ? $1 . "- \"" . $secondary . "\"\n" : ""/gme;

    my %repl = (
      "__CONTROL_PLANE_NAME__" => $ENV{"CONTROL_PLANE_NAME"},
      "__ENV_TAG_LOWER__" => $ENV{"ENV_TAG_LOWER"},
      "__INTERNAL_TLS_HOST__" => $ENV{"INTERNAL_TLS_HOST"},
      "__PUBLIC_HOST_PRIMARY__" => $ENV{"PUBLIC_HOST_PRIMARY"},
      "__PUBLIC_HOST_PRIMARY_TLS__" => $ENV{"PUBLIC_HOST_PRIMARY"} . ":443",
      "__AML_REST_SERVICE_HOST__" => $ENV{"AML_REST_SERVICE_HOST"},
      "__BANCAWEB_SERVICE_HOST__" => $ENV{"BANCAWEB_SERVICE_HOST"},
      "__CLAIMHISTORY_STORM_SERVICE_HOST__" => $ENV{"CLAIMHISTORY_STORM_SERVICE_HOST"},
      "__KYC_WSMANAGER_SERVICE_HOST__" => $ENV{"KYC_WSMANAGER_SERVICE_HOST"},
      "__GET_TOKEN_SERVICE_NAME__" => $ENV{"GET_TOKEN_SERVICE_NAME"},
      "__GET_TOKEN_SERVICE_HOST__" => $ENV{"GET_TOKEN_SERVICE_HOST"},
      "__ISSUER_URL__" => $ENV{"ISSUER_URL"},
      "__REDIS_HOST__" => $ENV{"REDIS_HOST"},
      "__REDIS_PASSWORD__" => $ENV{"REDIS_PASSWORD"},
      "__REDIS_PARTIAL_ID__" => $ENV{"REDIS_PARTIAL_ID"},
      "__REDIS_PARTIAL_NAME__" => $ENV{"REDIS_PARTIAL_NAME"},
      "__REDIS_PARTIAL_TYPE__" => $ENV{"REDIS_PARTIAL_TYPE"},
      "__REDIS_PARTIAL_HOST__" => $ENV{"REDIS_PARTIAL_HOST"},
      "__REDIS_PARTIAL_PASSWORD__" => $ENV{"REDIS_PARTIAL_PASSWORD"},
      "__REDIS_PARTIAL_SENTINEL_MASTER__" => $ENV{"REDIS_PARTIAL_SENTINEL_MASTER"},
      "__REDIS_PARTIAL_SENTINEL_NODES__" => $ENV{"REDIS_PARTIAL_SENTINEL_NODES"},
      "__REDIS_PARTIAL_SENTINEL_PASSWORD__" => $ENV{"REDIS_PARTIAL_SENTINEL_PASSWORD"},
      "__REDIS_PARTIAL_SENTINEL_ROLE__" => $ENV{"REDIS_PARTIAL_SENTINEL_ROLE"},
      "__REDIS_PARTIAL_SENTINEL_USERNAME__" => $ENV{"REDIS_PARTIAL_SENTINEL_USERNAME"},
      "__REDIS_CACHE_PARTIAL_ID__" => $ENV{"REDIS_CACHE_PARTIAL_ID"},
      "__REDIS_CACHE_PARTIAL_NAME__" => $ENV{"REDIS_CACHE_PARTIAL_NAME"},
      "__REDIS_CACHE_HOST__" => $ENV{"REDIS_CACHE_HOST"},
      "__REDIS_CACHE_PASSWORD__" => $ENV{"REDIS_CACHE_PASSWORD"},
      "__REDIS_CACHE_SENTINEL_MASTER__" => $ENV{"REDIS_CACHE_SENTINEL_MASTER"},
      "__REDIS_CACHE_SENTINEL_NODES__" => $ENV{"REDIS_CACHE_SENTINEL_NODES"},
      "__REDIS_CACHE_SENTINEL_PASSWORD__" => $ENV{"REDIS_CACHE_SENTINEL_PASSWORD"},
      "__REDIS_CACHE_SENTINEL_ROLE__" => $ENV{"REDIS_CACHE_SENTINEL_ROLE"},
      "__REDIS_CACHE_SENTINEL_USERNAME__" => $ENV{"REDIS_CACHE_SENTINEL_USERNAME"},
      "__DR_REDIS_PARTIAL_ID__" => $ENV{"DR_REDIS_PARTIAL_ID"},
      "__DR_REDIS_PARTIAL_NAME__" => $ENV{"DR_REDIS_PARTIAL_NAME"},
      "__DR_REDIS_PARTIAL_TYPE__" => $ENV{"DR_REDIS_PARTIAL_TYPE"},
      "__DR_REDIS_PARTIAL_HOST__" => $ENV{"DR_REDIS_PARTIAL_HOST"},
      "__DR_REDIS_PARTIAL_PASSWORD__" => $ENV{"DR_REDIS_PARTIAL_PASSWORD"},
      "__DR_REDIS_PARTIAL_SENTINEL_MASTER__" => $ENV{"DR_REDIS_PARTIAL_SENTINEL_MASTER"},
      "__DR_REDIS_PARTIAL_SENTINEL_NODES__" => $ENV{"DR_REDIS_PARTIAL_SENTINEL_NODES"},
      "__DR_REDIS_PARTIAL_SENTINEL_PASSWORD__" => $ENV{"DR_REDIS_PARTIAL_SENTINEL_PASSWORD"},
      "__DR_REDIS_PARTIAL_SENTINEL_ROLE__" => $ENV{"DR_REDIS_PARTIAL_SENTINEL_ROLE"},
      "__DR_REDIS_PARTIAL_SENTINEL_USERNAME__" => $ENV{"DR_REDIS_PARTIAL_SENTINEL_USERNAME"},
      "__DR_REDIS_CACHE_PARTIAL_ID__" => $ENV{"DR_REDIS_CACHE_PARTIAL_ID"},
      "__DR_REDIS_CACHE_PARTIAL_NAME__" => $ENV{"DR_REDIS_CACHE_PARTIAL_NAME"},
      "__DR_REDIS_CACHE_HOST__" => $ENV{"DR_REDIS_CACHE_HOST"},
      "__DR_REDIS_CACHE_PASSWORD__" => $ENV{"DR_REDIS_CACHE_PASSWORD"},
      "__DR_REDIS_CACHE_SENTINEL_MASTER__" => $ENV{"DR_REDIS_CACHE_SENTINEL_MASTER"},
      "__DR_REDIS_CACHE_SENTINEL_NODES__" => $ENV{"DR_REDIS_CACHE_SENTINEL_NODES"},
      "__DR_REDIS_CACHE_SENTINEL_PASSWORD__" => $ENV{"DR_REDIS_CACHE_SENTINEL_PASSWORD"},
      "__DR_REDIS_CACHE_SENTINEL_ROLE__" => $ENV{"DR_REDIS_CACHE_SENTINEL_ROLE"},
      "__DR_REDIS_CACHE_SENTINEL_USERNAME__" => $ENV{"DR_REDIS_CACHE_SENTINEL_USERNAME"},
      "__VAULT_CONFIG_STORE_ID__" => $ENV{"VAULT_CONFIG_STORE_ID"},
      "__STANDARD_AMLA_API_RATE_LIMIT_MINUTE__" => $ENV{"STANDARD_AMLA_API_RATE_LIMIT_MINUTE"},
      "__STANDARD_AMLA_API_RATE_LIMIT_HOUR__" => $ENV{"STANDARD_AMLA_API_RATE_LIMIT_HOUR"},
      "__STANDARD_BANCA_PORTAL_RATE_LIMIT_MINUTE__" => $ENV{"STANDARD_BANCA_PORTAL_RATE_LIMIT_MINUTE"},
      "__STANDARD_BANCA_PORTAL_RATE_LIMIT_HOUR__" => $ENV{"STANDARD_BANCA_PORTAL_RATE_LIMIT_HOUR"},
      "__STANDARD_CLAIM_HISTORY_RATE_LIMIT_MINUTE__" => $ENV{"STANDARD_CLAIM_HISTORY_RATE_LIMIT_MINUTE"},
      "__STANDARD_CLAIM_HISTORY_RATE_LIMIT_HOUR__" => $ENV{"STANDARD_CLAIM_HISTORY_RATE_LIMIT_HOUR"},
      "__STANDARD_AMLA_API_USER_CUSTOM_ID__" => $ENV{"STANDARD_AMLA_API_USER_CUSTOM_ID"},
      "__STANDARD_BANCA_PORTAL_USER_CUSTOM_ID__" => $ENV{"STANDARD_BANCA_PORTAL_USER_CUSTOM_ID"},
      "__STANDARD_CLAIM_HISTORY_USER_CUSTOM_ID__" => $ENV{"STANDARD_CLAIM_HISTORY_USER_CUSTOM_ID"},
    );
    s/(__CONTROL_PLANE_NAME__|__ENV_TAG_LOWER__|__INTERNAL_TLS_HOST__|__PUBLIC_HOST_PRIMARY__|__PUBLIC_HOST_PRIMARY_TLS__|__AML_REST_SERVICE_HOST__|__BANCAWEB_SERVICE_HOST__|__CLAIMHISTORY_STORM_SERVICE_HOST__|__KYC_WSMANAGER_SERVICE_HOST__|__GET_TOKEN_SERVICE_NAME__|__GET_TOKEN_SERVICE_HOST__|__ISSUER_URL__|__REDIS_HOST__|__REDIS_PASSWORD__|__REDIS_PARTIAL_ID__|__REDIS_PARTIAL_NAME__|__REDIS_PARTIAL_TYPE__|__REDIS_PARTIAL_HOST__|__REDIS_PARTIAL_PASSWORD__|__REDIS_PARTIAL_SENTINEL_MASTER__|__REDIS_PARTIAL_SENTINEL_NODES__|__REDIS_PARTIAL_SENTINEL_PASSWORD__|__REDIS_PARTIAL_SENTINEL_ROLE__|__REDIS_PARTIAL_SENTINEL_USERNAME__|__REDIS_CACHE_PARTIAL_ID__|__REDIS_CACHE_PARTIAL_NAME__|__REDIS_CACHE_HOST__|__REDIS_CACHE_PASSWORD__|__REDIS_CACHE_SENTINEL_MASTER__|__REDIS_CACHE_SENTINEL_NODES__|__REDIS_CACHE_SENTINEL_PASSWORD__|__REDIS_CACHE_SENTINEL_ROLE__|__REDIS_CACHE_SENTINEL_USERNAME__|__DR_REDIS_PARTIAL_ID__|__DR_REDIS_PARTIAL_NAME__|__DR_REDIS_PARTIAL_TYPE__|__DR_REDIS_PARTIAL_HOST__|__DR_REDIS_PARTIAL_PASSWORD__|__DR_REDIS_PARTIAL_SENTINEL_MASTER__|__DR_REDIS_PARTIAL_SENTINEL_NODES__|__DR_REDIS_PARTIAL_SENTINEL_PASSWORD__|__DR_REDIS_PARTIAL_SENTINEL_ROLE__|__DR_REDIS_PARTIAL_SENTINEL_USERNAME__|__DR_REDIS_CACHE_PARTIAL_ID__|__DR_REDIS_CACHE_PARTIAL_NAME__|__DR_REDIS_CACHE_HOST__|__DR_REDIS_CACHE_PASSWORD__|__DR_REDIS_CACHE_SENTINEL_MASTER__|__DR_REDIS_CACHE_SENTINEL_NODES__|__DR_REDIS_CACHE_SENTINEL_PASSWORD__|__DR_REDIS_CACHE_SENTINEL_ROLE__|__DR_REDIS_CACHE_SENTINEL_USERNAME__|__VAULT_CONFIG_STORE_ID__|__STANDARD_AMLA_API_RATE_LIMIT_MINUTE__|__STANDARD_AMLA_API_RATE_LIMIT_HOUR__|__STANDARD_BANCA_PORTAL_RATE_LIMIT_MINUTE__|__STANDARD_BANCA_PORTAL_RATE_LIMIT_HOUR__|__STANDARD_CLAIM_HISTORY_RATE_LIMIT_MINUTE__|__STANDARD_CLAIM_HISTORY_RATE_LIMIT_HOUR__|__STANDARD_AMLA_API_USER_CUSTOM_ID__|__STANDARD_BANCA_PORTAL_USER_CUSTOM_ID__|__STANDARD_CLAIM_HISTORY_USER_CUSTOM_ID__)/$repl{$1}/ge;
  ' "$file" > "${file}.tmp"
  mv "${file}.tmp" "$file"
done

if grep -R -n -E '__[A-Z0-9_]+__' "$OUTPUT_DIR" >/dev/null; then
  echo "Unresolved template tokens found in rendered output:"
  grep -R -n -E '__[A-Z0-9_]+__' "$OUTPUT_DIR"
  exit 1
fi

echo "Rendered Kong state to: $OUTPUT_DIR"
